
name: Build and Push mem0 Docker Images

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mem0 repository
        uses: actions/checkout@v3
        with:
          repository: mem0/mem0
          path: mem0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          context: ./mem0/openmemory/api
          file: ./mem0/openmemory/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mem0-api:latest

      - name: Build and push UI image
        uses: docker/build-push-action@v4
        with:
          context: ./mem0/openmemory/ui
          file: ./mem0/openmemory/ui/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mem0-ui:latest
