name: Build and Push mem0 Docker Images

on:
  push:
    paths:
      - "release-versions/*"
  # push:
  #   branches:
  #     - main
  # schedule:
  #   # - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Get current repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: build

      - name: Get the version of mem0 to build
        id: vars
        run: |
          echo "tag=$(cat build/release-versions/mem0-latest.txt)" >> $GITHUB_OUTPUT

      - name: Checkout mem0 repository
        uses: actions/checkout@v4
        with:
          repository: mem0ai/mem0
          path: mem0
          ref: v${{ steps.vars.outputs.tag }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./mem0/openmemory/api
          file: ./mem0/openmemory/api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mem0-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mem0-api:v${{ steps.vars.outputs.tag }}

      - name: Build and push UI image
        uses: docker/build-push-action@v4
        with:
          context: ./mem0/openmemory/ui
          file: ./mem0/openmemory/ui/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mem0-ui:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mem0-ui:v${{ steps.vars.outputs.tag }}
